services:
  guitarena-astro:
    build:
      context: .
      args:
        BUILD_DATE: ${BUILD_DATE:-unset}
    container_name: guitarena-astro
    restart: always
    ports:
      - "8080:80"
    networks:
      - guitarena-net

networks:
  guitarena-net:
    driver: bridge
